### ISSUE TITLE
Outdated mysql queries for db connect  

### ISSUE THREAD

**Issue by s4ndeeps** [offensive-security/masscan-web-ui#14]
Since now PHP 7 is now default installation on Ubuntu machine, can you guys **make the code php7 compatible**.  

````
Fatal error: Uncaught Error: Call to undefined function mysqli_connect() in /var/www/html/lib/mysql/class.mysql.php:16 Stack trace: #0 /var/www/html/lib/class.db.php(29): MySQL->__construct() #1 /var/www/html/lib/class.db.php(41): DB->__construct() #2 /var/www/html/lib/class.db.php(73): DB::getInstance() #3 /var/www/html/includes/functions.php(61): DB::fetchAll('SELECT ip AS ip...') #4 /var/www/html/includes/data_validation.php(44): browse(Array) #5 /var/www/html/index.php(5): require('/var/www/html/i...') #6 {main} thrown in /var/www/html/lib/mysql/class.mysql.php on line 16
````

**Comment by pawco** [comment]
Queries are not outdated, it seems that mysqli PHP extension is not installed on your server.
